import { useEffect, useRef, useState } from 'react';
import { ArrowSquareOut, ArrowsOutSimple, BookOpen, CaretDown, CaretRight, Check, CircleNotch, CloudArrowUp, Cube, DownloadSimple, FileText, FloppyDisk, Folder, Link, MagnifyingGlass, Microphone, Monitor, PencilSimple, Play, Plus, Scissors, Trash, UploadSimple, User, Waveform } from '@phosphor-icons/react';
import { api, duration, labels } from './api';
import type { Item, Entry, Settings } from './api';
import type { Shared } from './App';
import { Button, Empty } from './components';
import { readDraft, writeDraft } from './drafts';

export { Collect } from './Collection';
export { Library } from './Library';
import { FeishuSettings } from './Feishu';

export function ProcessText({ state, processingSource, refresh, select, notify, navigate }: Shared) {
  const [source, setSource] = useState(processingSource);
  const draftKey = `process-text-${processingSource || 'manual'}`;
  const [text, setText] = useState('');
  const [action, setAction] = useState('summary');
  const [instruction, setInstruction] = useState('');
  const [busy, setBusy] = useState(false);
  const [title, setTitle] = useState('新文稿');
  const [draftLoaded, setDraftLoaded] = useState(false);
  useEffect(() => { let cancelled = false; readDraft<{source:string;text:string;action:string;instruction:string;title:string}>(draftKey).then(async saved => {
    if (cancelled) return;
    if (saved) { setSource(saved.source); setText(saved.text); setAction(saved.action); setInstruction(saved.instruction); setTitle(saved.title); }
    else if (processingSource) { const i = await api<Item>(`/items/${processingSource}`); if (!cancelled) { setText(i.transcript); setTitle(i.title); } }
    if (!cancelled) setDraftLoaded(true);
  }).catch(e => notify(e.message,true)); return () => { cancelled = true; }; },[notify]);
  useEffect(() => { if (draftLoaded) writeDraft(draftKey, {source,text,action,instruction,title}).catch(e => notify('草稿保存失败：' + e.message,true)); },[source,text,action,instruction,title,draftLoaded,notify,draftKey]);
  function chooseSource(id:string) { navigate('process', id); }
  async function process() { setBusy(true); try { const item = await api<Item>('/process-text','POST',{text, action, instruction, title: title + ' · ' + ({summary:'摘要',correct:'校正',rewrite:'改写',translate:'翻译',outline:'大纲'}[action] || '')}); await refresh(); select(item.id); notify('处理结果已保存到输出库'); } catch(e) { notify((e as Error).message,true); } finally { setBusy(false); } }
  return <section className="panel writing-panel"><div className="panel-heading"><h2>选择原文</h2><select aria-label="选择原文" value={source} onChange={e => chooseSource(e.target.value)}><option value="">手动粘贴文稿</option>{state.items.filter(i => i.has_transcript).map(i => <option key={i.id} value={i.id}>{i.title}</option>)}</select></div><textarea aria-label="待处理文案" disabled={!draftLoaded} className="writing-area" placeholder="在这里粘贴正文，或从文稿库选择一份文稿…" value={text} onChange={e => setText(e.target.value)}/><div className="word-count">{text.length.toLocaleString()} 字 · 原始文稿会保留</div><h3>处理方式</h3><div className="action-options">{[['summary','提炼摘要'],['correct','错字校正'],['rewrite','文案改写'],['outline','拆解大纲'],['translate','中英翻译']].map(([v,l]) => <button className={action === v ? 'selected' : ''} key={v} onClick={() => setAction(v)}>{l}</button>)}</div><label className="field-label">补充要求<input placeholder="例如：保留所有数据，整理成适合口播的表达" value={instruction} onChange={e => setInstruction(e.target.value)}/></label><div className="service-note"><Cube size={18}/><span>{state.settings.llm_model ? `使用 ${state.settings.llm_model} · ${state.settings.llm_url}` : '还没有配置文本模型。支持 Ollama 与 OpenAI 兼容服务。'}</span><button onClick={() => navigate('models')}>配置模型</button></div><div className="form-actions"><span className="muted">正文会发送到你配置的模型服务</span><Button primary disabled={busy || !text.trim() || !state.settings.llm_model} onClick={process}>{busy ? <CircleNotch size={16} className="spin"/> : <Play size={16}/>} {busy ? '正在处理全文…' : '开始处理'}</Button></div></section>;
}

export function Voice({ state, selected, refresh, select, notify }: Shared) {
  const [text, setText] = useState(''); const [source,setSource] = useState('');
  const [voices, setVoices] = useState<{id?:string;name:string;language:string;gender?:string;engine?:string}[]>([]); const [voice,setVoice] = useState('');
  const [rate,setRate] = useState('0'); const [busy,setBusy] = useState(false);
  useEffect(() => { api<{id?:string;name:string;language:string;gender?:string;engine?:string}[]>('/voices').then(v => { setVoices(v); const preferred=v.find(i=>i.name.includes('Huihui'))||v.find(i=>i.language.startsWith('zh'));setVoice(preferred?.id||preferred?.name||v[0]?.id||v[0]?.name||''); }).catch(e => notify(e.message,true)); },[notify]);
  useEffect(() => { if (source) api<Item>(`/items/${source}`).then(i => setText(i.transcript)).catch(e => notify(e.message,true)); },[source,notify]);
  async function generate() { setBusy(true); try { const item = await api<Item>('/voice','POST',{text,voice,rate:Number(rate),title:(state.items.find(i => i.id === source)?.title || '本地配音') + ' · 配音'}); await refresh(); select(item.id); notify('配音已保存到音频库'); } catch(e) { notify((e as Error).message,true); } finally { setBusy(false); } }
  return <section className="panel writing-panel"><div className="panel-heading"><h2><Microphone size={19}/>配音正文</h2><select aria-label="选择配音文稿" value={source} onChange={e => setSource(e.target.value)}><option value="">手动输入正文</option>{state.items.filter(i => i.has_transcript).map(i => <option key={i.id} value={i.id}>{i.title}</option>)}</select></div><textarea aria-label="配音正文" className="writing-area" value={text} onChange={e => setText(e.target.value)} placeholder="写下希望读出的内容。只会朗读这里的正文。"/><div className="form-grid voice-options"><label>本地音色<select aria-label="本地音色" value={voice} onChange={e => setVoice(e.target.value)}>{voices.map(v => <option key={v.id||v.name} value={v.id||v.name}>{v.name} · {v.gender==='male'?'男声':v.gender==='female'?'女声':'系统音色'} · {v.language}</option>)}</select></label><label>语速<select aria-label="语速" value={rate} onChange={e => setRate(e.target.value)}><option value="-2">稍慢</option><option value="0">正常</option><option value="2">稍快</option></select></label></div><div className="service-note"><Monitor size={19}/><span>已读取 {voices.length} 个 Windows 音色，包含现代系统语音和桌面语音；全部在本机离线生成 WAV 音频。</span></div><div className="form-actions"><span className="muted">{text.length.toLocaleString()} 字</span><Button primary disabled={busy || !text.trim() || !voices.length} onClick={generate}>{busy ? <CircleNotch size={16} className="spin"/> : <Microphone size={16}/>} {busy ? '正在生成配音…' : '生成配音'}</Button></div></section>;
}

export function Clip({state,refresh,select,notify}:Shared) {
  const [source,setSource] = useState(''); const [start,setStart] = useState('0'); const [end,setEnd] = useState('10'); const [busy,setBusy] = useState(false);
  const selected = state.items.find(i => i.id === source);
  async function clip() { setBusy(true); try { const item = await api<Item>('/clip','POST',{item_id:source,start:Number(start),end:Number(end)}); await refresh(); select(item.id); notify('片段已保存到切片库'); } catch(e) { notify((e as Error).message,true); } finally { setBusy(false); } }
  return <section className="panel writing-panel"><label className="field-label">选择本地录播或素材<select aria-label="切片源素材" value={source} onChange={e => { setSource(e.target.value); const item=state.items.find(i=>i.id===e.target.value); if(item) setEnd(String(Math.min(30,item.duration || 30))); }}><option value="">选择已导入的音视频</option>{state.items.filter(i => i.media_path).map(i => <option key={i.id} value={i.id}>{i.title} · {duration(i.duration)}</option>)}</select></label>{selected?.media_path && <video className="clip-preview" controls src={`/api/items/${selected.id}/media`}/>}<div className="form-grid voice-options"><label>开始时间（秒）<input aria-label="切片开始时间" type="number" min="0" step="0.1" value={start} onChange={e=>setStart(e.target.value)}/></label><label>结束时间（秒）<input aria-label="切片结束时间" type="number" min="0" step="0.1" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="service-note"><Scissors size={19}/><span>按选定时间生成独立文件，保留原始素材。当前支持已下载的录播文件。</span></div><div className="form-actions"><Button primary disabled={!source || busy} onClick={clip}>{busy ? <CircleNotch size={16} className="spin"/> : <Scissors size={16}/>} {busy?'正在生成片段…':'保存片段'}</Button></div></section>;
}

export function Models({ state,refresh,notify }:Shared) {
  const [tab,setTab] = useState('transcription'); const [draft,setDraft] = useState<Settings>({}); const [loaded,setLoaded] = useState(false); const [pending,setPending] = useState('');
  useEffect(()=>{ if(!loaded && Object.keys(state.settings).length) { setDraft(state.settings); setLoaded(true); } },[state.settings,loaded]);
  async function action(id:string,operation:string) { setPending(id); try { await api(`/models/${id}${operation==='install'?'/install':''}`,operation==='install'?'POST':'DELETE'); await refresh(); notify(operation==='install'?'模型开始下载，可以在这里查看状态':'模型已卸载'); } catch(e) { notify((e as Error).message,true); } finally { setPending(''); } }
  async function save() { try { await api('/settings','PATCH',draft); await refresh(); setDraft(d=>({...d,llm_api_key:''})); notify('文本模型配置已保存'); } catch(e) { notify((e as Error).message,true); } }
  return <section className="panel models-panel"><div className="settings-tabs"><button className={tab==='transcription'?'selected':''} onClick={()=>setTab('transcription')}>本地语音转录</button><button className={tab==='text'?'selected':''} onClick={()=>setTab('text')}>文本处理模型</button></div>{tab==='transcription'?<><div className="model-intro"><Cube size={24}/><div><h2>在你的电脑上完成转录</h2><p>首次下载模型后可离线使用。当前采用 CPU · INT8 量化。</p></div><label>识别语言<select aria-label="识别语言" value={String(state.settings.language||'auto')} onChange={async e=>{try{await api('/settings','PATCH',{language:e.target.value});await refresh();}catch(err){notify((err as Error).message,true);}}}><option value="auto">自动识别（中英文）</option><option value="zh">仅中文</option><option value="en">仅英语</option><option value="ja">仅日语</option><option value="ko">仅韩语</option></select></label></div><div className="models-list">{state.models.map(m=><article className="model-row" key={m.id}><div className="model-glyph"><Cube size={25}/></div><div className="model-description"><h3>{m.name}{state.settings.model===m.id && <span className="status-pill done">当前使用</span>}</h3><p>{m.note}</p><small>{m.size} · {m.message || (m.installed?'已安装，可离线使用':'尚未安装')}</small>{m.state==='downloading' && <progress/>}</div><div className="model-actions">{m.installed?<><Button disabled={state.settings.model===m.id} primary={state.settings.model!==m.id} onClick={async()=>{await api('/settings','PATCH',{model:m.id});await refresh();notify(`已切换到 ${m.name}`);}}><Check size={14}/>{state.settings.model===m.id?'使用中':'使用此模型'}</Button><Button title={`卸载 ${m.name}`} disabled={pending===m.id} onClick={()=>action(m.id,'delete')}><Trash size={15}/></Button></>:<Button primary disabled={m.state==='downloading'||pending===m.id} onClick={()=>action(m.id,'install')}>{m.state==='downloading'?<CircleNotch size={15} className="spin"/>:<DownloadSimple size={15}/>} {m.state==='downloading'?'下载中…':m.state==='error'?'重试下载':'下载模型'}</Button>}</div></article>)}</div><p className="footnote">建议使用自动识别：中文统一输出简体，英文保留英文。需要强制某种语言时再手动选择。</p></>:<div className="settings-form"><h2>连接文本模型</h2><p>支持 DeepSeek、Ollama 等 OpenAI 兼容服务。这里应填写 API 服务地址。</p><label>服务地址<input aria-label="文本模型服务地址" value={String(draft.llm_url||'')} onChange={e=>setDraft({...draft,llm_url:e.target.value})} placeholder="例如：https://api.deepseek.com"/></label><label>模型名称<input aria-label="文本模型名称" value={String(draft.llm_model||'')} onChange={e=>setDraft({...draft,llm_model:e.target.value})} placeholder="例如：deepseek-flash"/></label><label>API Key（本地服务可留空）<input type="password" autoComplete="off" value={String(draft.llm_api_key||'')} onChange={e=>setDraft({...draft,llm_api_key:e.target.value})} placeholder={state.settings.has_llm_key?'已保存，留空保持不变':'仅在服务需要时填写'}/></label><p className="footnote">DeepSeek 请填写 api.deepseek.com，不要粘贴 platform.deepseek.com 的密钥管理页面。</p><div className="form-actions"><Button primary onClick={save}><FloppyDisk size={16}/>保存配置</Button></div></div>}</section>;
}

export function Configuration(props:Shared & {page:string}) {
  const {state,refresh,notify,page}=props;
  const [tab,setTab] = useState(page==='feishu'?'feishu':page==='obsidian'?'files':'general'); const [draft,setDraft] = useState<Settings>({}); const [loaded,setLoaded]=useState(false); const [saving,setSaving]=useState(false); const file=useRef<HTMLInputElement>(null);
  useEffect(()=>{setTab(page==='feishu'?'feishu':page==='obsidian'?'files':'general');},[page]);
  useEffect(()=>{if(!loaded && Object.keys(state.settings).length){setDraft(state.settings);setLoaded(true);}},[state.settings,loaded]);
  const set=(k:string,v:string)=>setDraft({...draft,[k]:v});
  async function save(){setSaving(true);try{await api('/settings','PATCH',draft);await refresh();setDraft(d=>({...d,feishu_secret:''}));notify('设置已保存');}catch(e){notify((e as Error).message,true);}finally{setSaving(false);}}
  function field(key:string,title:string,placeholder='',secret=false){return <label key={key}>{title}<input aria-label={title} autoComplete="off" type={secret?'password':'text'} value={String(draft[key]||'')} placeholder={placeholder} onChange={e=>set(key,e.target.value)}/></label>;}
  return <section className="panel settings-layout"><nav className="settings-nav" aria-label="设置分类">{[['general','通用'],['appearance','外观'],['files','文件与存储'],['feishu','飞书知识库'],['about','关于']].map(([v,l])=><button className={tab===v?'selected':''} key={v} onClick={()=>setTab(v)}>{l}</button>)}</nav><div className="settings-form">{tab==='general' && <><h2>采集与登录</h2><p>公开作品可以直接尝试采集。平台需要登录时，手动导入你自己导出的 Netscape 格式 Cookie 文件。</p><div className="setting-row"><div><strong>平台登录文件</strong><p>{state.settings.cookies_path?'已导入 cookies.txt':'尚未导入，使用公开内容模式'}</p></div><Button onClick={()=>file.current?.click()}><UploadSimple size={16}/>导入 cookies.txt</Button>{state.settings.cookies_path && <Button onClick={async()=>{await api('/cookies','DELETE');await refresh();notify('已清除登录文件');}}>清除</Button>}</div><input hidden type="file" accept=".txt" ref={file} onChange={async e=>{if(e.target.files?.[0]){const form=new FormData();form.append('file',e.target.files[0]);try{await api('/cookies','POST',form);await refresh();notify('登录文件已导入');}catch(err){notify((err as Error).message,true);}finally{e.target.value='';}}}}/><div className="service-note"><Monitor size={20}/><span>程序仅连接本地界面服务。音视频转录在这台电脑上完成。</span></div><h2>任务恢复</h2><p>关闭后再次打开，文稿与任务仍会保留。未完成任务会标记为已暂停，点击开始即可重新处理；已下载文件会继续使用。</p></>}{tab==='appearance' && <><h2>外观</h2><p>沿用录屏中的米白面板与蓝绿色控件，也可以切换深色外观。</p><label>颜色主题<select aria-label="颜色主题" value={String(draft.theme||'light')} onChange={e=>set('theme',e.target.value)}><option value="light">浅色 · 米白</option><option value="dark">深色 · 石墨</option></select></label></>}{tab==='files' && <><h2>文件与存储</h2><label>本地数据目录<div className="path-display">{state.data_dir}</div></label><Button onClick={()=>window.desktop?.openData()}><Folder size={16}/>打开数据文件夹</Button><p>素材、转录模型、文稿数据库和生成文件保存在此目录。移除列表条目不会删除源文件。</p><h2>Obsidian 知识库</h2>{field('obsidian_path','已有仓库文件夹','例如 D:\\Notes\\MyVault')}<Button onClick={async()=>{const p=await window.desktop?.chooseFolder();if(p)set('obsidian_path',p);}}><Folder size={16}/>选择仓库</Button><p>在右侧文稿预览中点击书本按钮，即可把文稿保存到仓库内的 Lulu 文件夹。</p></>}{tab==='feishu' && <FeishuSettings {...props}/>}{tab==='about' && <><div className="about-brand"><img src="/app-icon.svg" alt="Lulu"/><h2>Lulu Workbench</h2><span>0.1.0</span></div><p>根据你提供的 Lulu 录屏和公开功能说明独立实现。本项目不是 Lulu 官方 Windows 发行版。</p><p>本地转录：faster-whisper<br/>内容采集：yt-dlp<br/>音视频处理：FFmpeg<br/>界面：React + Electron</p><p>当前支持：本地转录、文稿管理、内容采集、文本模型接入、Windows 配音、录播切片、Markdown 与飞书文本导出。</p><p>语音克隆、实时直播录制和自动更新尚未实现。不同平台的链接采集结果取决于平台限制和登录状态。</p></>}{!['about','feishu'].includes(tab) && <div className="form-actions"><Button primary disabled={saving} onClick={save}><FloppyDisk size={16}/>{saving?'正在保存…':'保存设置'}</Button></div>}</div></section>;
}
